### PR TITLE
new parser combinators for fix-engine

### PR DESCRIPTION
**Pull request by c-cube**
This is an attempt at writing new parser combinators for FIX that should, hopefully, allocate a lot less and be faster overall. The parsing code will need to be changed but hopefully it's quite straightforward (I'll do it if this is greenlighted).

### CODE REVIEW

**Comment by ewenmaclean** [comment]
This looks great and seems to build and load fine with ipl models - also round trip tests work (check parse/json_encode/json_decode/encode round trip) works - related ipl PR which uses this SHA:
https://github.com/imandra-ai/ipl/pull/1223

**Comment by c-cube** [comment]
The new parser combinators are not used yet, but if you think they look good, @ewenmaclean, I'll start migrating to them in this branch?

**Comment by c-cube** [comment]
not sure how to test that now.

**Comment by ewenmaclean** [comment]
> not sure how to test that now.

I'll update the associated ipl branch and see how it looks passing this code through imandra

**Review by ewenmaclean — APPROVED** [review]

**Pull request merged**
